# Generated by Django 5.2 on 2025-08-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("facility_approval", "Facility Approval"),
                    ("facility_rejection", "Facility Rejection"),
                    ("user_ban", "User Ban"),
                    ("user_unban", "User Unban"),
                    ("report_resolution", "Report Resolution"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facility_reports_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
