# Generated by Django 5.2 on 2025-08-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0002_alter_adminaction_action_type_alter_report_reporter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("owner_response", models.TextField(blank=True)),
                ("owner_responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="facilities.facility",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "rating"],
                        name="reviews_rev_facilit_53e499_idx",
                    ),
                    models.Index(
                        fields=["user"], name="reviews_rev_user_id_a65d48_idx"
                    ),
                ],
            },
        ),
    ]
